"""initial schema

Revision ID: 3bb1f0f0a294
Revises:
Create Date: 2026-07-20 15:29:05.479219

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3bb1f0f0a294"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cameras",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('CONNECTED', 'DISCONNECTED', 'RECONNECTING')", name="ck_cameras_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')",
            name="ck_system_events_severity",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "camera_calibrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("homography_matrix", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reference_points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("calibrated_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_camera_calibrations_camera_id"), "camera_calibrations", ["camera_id"], unique=False
    )
    op.create_table(
        "camera_stream_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("rtsp_url_encrypted", sa.String(), nullable=False),
        sa.Column("transport", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_camera_stream_profiles_camera_id"),
        "camera_stream_profiles",
        ["camera_id"],
        unique=False,
    )
    op.create_table(
        "human_review_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("resolution", sa.String(), nullable=True),
        sa.Column("resolved_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('OPEN', 'CONFIRMED_MILITARY', 'CONFIRMED_CIVILIAN', "
            "'ESCALATED', 'DISMISSED')",
            name="ck_human_review_items_status",
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_human_review_items_camera_id"), "human_review_items", ["camera_id"], unique=False
    )
    op.create_index(
        op.f("ix_human_review_items_status"), "human_review_items", ["status"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("incident_type", sa.Enum("THREAT", name="incident_type"), nullable=False),
        sa.Column(
            "threat_level",
            sa.Enum(
                "ALLY", "OBSERVE", "LOW", "MEDIUM", "HIGH", "HUMAN_REVIEW", name="threat_level"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW", "ACTIVE", "ACKNOWLEDGED", "RESOLVED", "ARCHIVED", name="incident_status"
            ),
            nullable=False,
        ),
        sa.Column("threat_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incidents_camera_id"), "incidents", ["camera_id"], unique=False)
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_index(
        "ux_incidents_active_camera_track",
        "incidents",
        ["camera_id", "track_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('NEW', 'ACTIVE', 'ACKNOWLEDGED')"),
    )
    op.create_table(
        "incident_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("event_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_events_incident_id"), "incident_events", ["incident_id"], unique=False
    )
    op.create_table(
        "recordings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recordings_incident_id"), "recordings", ["incident_id"], unique=False)
    op.create_table(
        "snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_snapshots_incident_id"), "snapshots", ["incident_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_snapshots_incident_id"), table_name="snapshots")
    op.drop_table("snapshots")
    op.drop_index(op.f("ix_recordings_incident_id"), table_name="recordings")
    op.drop_table("recordings")
    op.drop_index(op.f("ix_incident_events_incident_id"), table_name="incident_events")
    op.drop_table("incident_events")
    op.drop_index(
        "ux_incidents_active_camera_track",
        table_name="incidents",
        postgresql_where=sa.text("status IN ('NEW', 'ACTIVE', 'ACKNOWLEDGED')"),
    )
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_camera_id"), table_name="incidents")
    op.drop_table("incidents")
    # op.drop_table() does not drop the Postgres ENUM types it created --
    # they must be dropped explicitly or upgrade() fails on a re-run with
    # "type already exists".
    sa.Enum(name="incident_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="threat_level").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="incident_type").drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f("ix_human_review_items_status"), table_name="human_review_items")
    op.drop_index(op.f("ix_human_review_items_camera_id"), table_name="human_review_items")
    op.drop_table("human_review_items")
    op.drop_index(op.f("ix_camera_stream_profiles_camera_id"), table_name="camera_stream_profiles")
    op.drop_table("camera_stream_profiles")
    op.drop_index(op.f("ix_camera_calibrations_camera_id"), table_name="camera_calibrations")
    op.drop_table("camera_calibrations")
    op.drop_table("users")
    op.drop_table("system_events")
    op.drop_table("cameras")
    # ### end Alembic commands ###
